### PR TITLE
Quick and dirty retry logic

### PR DESCRIPTION
**Pull request by rkoster**
This PR implements a quick and dirty solution for the problem raised in https://github.com/cloudfoundry/vcap-services-base/issues/21

### CODE REVIEW

**Comment by shalako** [comment]
Give us a day or two to figure out whether we can move this repo to cloudfoundry-community. There's a CAB call tomorrow.

**Comment by shalako** [comment]
Hello @rkoster so the guidance from the Foundation is we should move this repo to cloudfoundry-attic, and you should fork it into cloudfoundry-community to live on as long as you'd like to maintain it. 

Would you like to fork now, and we can update the README on this one to point to your fork? Then you can make the change in this PR directly and we'll close this PR without merge.

Thank you!

**Comment by rkoster** [comment]
@shalako the fork has been created in [cloudfoundry-community](https://github.com/cloudfoundry-community/vcap-services-base) will merge the PR there thanks

**Comment by shalako** [comment]
Thank you, @rkoster. I've updated the README on our copy to point to yours. We'll be moving our repo to cloudfoundry-attic.

**Pull request closed without merging**
